/*
 * INCOGNITO CONFIDENTIAL 
 * 
 * [2018] Incognito Solutions 
 * All Rights Reserved.
 * 
 * NOTICE:  All information contained herein is, and remains
 * the property of Incognito Solutions and its client.
 * The intellectual and technical concepts contained
 * herein are proprietary to Adobe Systems Incorporated
 * and its client and may be covered by U.S. and Foreign Patents
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Incognito Solutions.
 */
package ph.com.incognitosolutions.aei.view;

import javax.swing.ButtonGroup;

/**
 *
 * @author loretizoj
 */
public class ClientPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClientPanel
     */
    public ClientPanel() {
        initComponents();
        
        ButtonGroup bGroup = new ButtonGroup();
        bGroup.add(rbSingle);
        bGroup.add(rbMarried);
        setSpouseToVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        TabClientDetails = new javax.swing.JPanel();
        headerClient = new javax.swing.JLabel();
        lblCivilStatus = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblSpouseIDType = new javax.swing.JLabel();
        lblSpouseName = new javax.swing.JLabel();
        lblSpouseIDNo = new javax.swing.JLabel();
        headerSpousePartner = new javax.swing.JLabel();
        lblIDNumber = new javax.swing.JLabel();
        lblIDType = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        tfName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        tfAge = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        tfAddress = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        tfIdNumber = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        tdIdType = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jTextField10 = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jTextField14 = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jTextField15 = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jTextField16 = new javax.swing.JTextField();
        rbMarried = new javax.swing.JRadioButton();
        rbSingle = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        headerWitness = new javax.swing.JLabel();
        lblWitness1 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jTextField11 = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jTextField13 = new javax.swing.JTextField();
        lblWitness2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        headerHouse = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        tfName1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblName2 = new javax.swing.JLabel();
        tfName2 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        lblName3 = new javax.swing.JLabel();
        tfName3 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        lblName4 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        tfName4 = new javax.swing.JTextField();
        tfName5 = new javax.swing.JTextField();
        lblName5 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        lblName6 = new javax.swing.JLabel();
        tfName6 = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        lblName7 = new javax.swing.JLabel();
        tfName7 = new javax.swing.JTextField();
        tfName8 = new javax.swing.JTextField();
        lblName8 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        lblName9 = new javax.swing.JLabel();
        tfName9 = new javax.swing.JTextField();
        jSeparator21 = new javax.swing.JSeparator();
        headerHouse1 = new javax.swing.JLabel();
        lblName10 = new javax.swing.JLabel();
        tfName10 = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        lblName11 = new javax.swing.JLabel();
        lblName12 = new javax.swing.JLabel();
        lblName13 = new javax.swing.JLabel();
        tfName11 = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        tfName12 = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        tfName13 = new javax.swing.JTextField();
        jSeparator25 = new javax.swing.JSeparator();
        headerHouse2 = new javax.swing.JLabel();
        lblName14 = new javax.swing.JLabel();
        tfName14 = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        lblName15 = new javax.swing.JLabel();
        tfName15 = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        lblName16 = new javax.swing.JLabel();
        tfName16 = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 460));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 153, 51));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        TabClientDetails.setBackground(new java.awt.Color(255, 255, 255));
        TabClientDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerClient.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        headerClient.setForeground(new java.awt.Color(102, 102, 102));
        headerClient.setText("Client Personal Information");
        TabClientDetails.add(headerClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblCivilStatus.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblCivilStatus.setForeground(new java.awt.Color(102, 102, 102));
        lblCivilStatus.setText("Civil Status:");
        lblCivilStatus.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblCivilStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 80, -1));

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setText("Name:");
        lblName.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        lblAge.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblAge.setForeground(new java.awt.Color(102, 102, 102));
        lblAge.setText("Age:");
        lblAge.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 40, -1));

        lblBirthdate.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblBirthdate.setForeground(new java.awt.Color(102, 102, 102));
        lblBirthdate.setText("Birthdate:");
        lblBirthdate.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblBirthdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 70, -1));

        lblAddress.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(102, 102, 102));
        lblAddress.setText("Address:");
        lblAddress.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, -1));

        lblContact.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblContact.setForeground(new java.awt.Color(102, 102, 102));
        lblContact.setText("Contact #:");
        lblContact.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, -1));

        lblSpouseIDType.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSpouseIDType.setForeground(new java.awt.Color(102, 102, 102));
        lblSpouseIDType.setText("ID Type:");
        lblSpouseIDType.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblSpouseIDType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 60, -1));

        lblSpouseName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSpouseName.setForeground(new java.awt.Color(102, 102, 102));
        lblSpouseName.setText("Name:");
        lblSpouseName.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblSpouseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        lblSpouseIDNo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSpouseIDNo.setForeground(new java.awt.Color(102, 102, 102));
        lblSpouseIDNo.setText("ID Number:");
        lblSpouseIDNo.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblSpouseIDNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 80, -1));

        headerSpousePartner.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        headerSpousePartner.setForeground(new java.awt.Color(102, 102, 102));
        headerSpousePartner.setText("Spouse Information");
        TabClientDetails.add(headerSpousePartner, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        lblIDNumber.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblIDNumber.setForeground(new java.awt.Color(102, 102, 102));
        lblIDNumber.setText("ID Number:");
        lblIDNumber.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblIDNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 80, -1));

        lblIDType.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblIDType.setForeground(new java.awt.Color(102, 102, 102));
        lblIDType.setText("ID Type:");
        lblIDType.setPreferredSize(new java.awt.Dimension(43, 25));
        TabClientDetails.add(lblIDType, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 60, -1));

        btnCancel.setBackground(java.awt.Color.red);
        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/cancel.png"))); // NOI18N
        btnCancel.setText(" Cancel");
        btnCancel.setMinimumSize(new java.awt.Dimension(95, 30));
        btnCancel.setPreferredSize(new java.awt.Dimension(95, 30));
        TabClientDetails.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 110, 30));

        btnSave.setBackground(new java.awt.Color(0, 204, 0));
        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/save.png"))); // NOI18N
        btnSave.setText(" Save");
        btnSave.setPreferredSize(new java.awt.Dimension(95, 30));
        TabClientDetails.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 110, 30));

        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 220, -1));

        tfName.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName.setForeground(new java.awt.Color(255, 153, 51));
        tfName.setBorder(null);
        TabClientDetails.add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 220, -1));

        jSeparator3.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, -1));

        tfAge.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfAge.setForeground(new java.awt.Color(255, 153, 51));
        tfAge.setBorder(null);
        TabClientDetails.add(tfAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, -1));

        jSeparator4.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 220, -1));

        jSeparator6.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 220, -1));

        tfAddress.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfAddress.setForeground(new java.awt.Color(255, 153, 51));
        tfAddress.setBorder(null);
        TabClientDetails.add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, -1));

        jSeparator7.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, -1));

        tfIdNumber.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfIdNumber.setForeground(new java.awt.Color(255, 153, 51));
        tfIdNumber.setBorder(null);
        TabClientDetails.add(tfIdNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, -1));

        jSeparator9.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, -1));

        tdIdType.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tdIdType.setForeground(new java.awt.Color(255, 153, 51));
        tdIdType.setBorder(null);
        TabClientDetails.add(tdIdType, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 220, -1));

        jSeparator10.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 220, -1));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 153, 51));
        jTextField10.setBorder(null);
        TabClientDetails.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, -1));

        jSeparator14.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 220, -1));

        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 153, 51));
        jTextField14.setBorder(null);
        TabClientDetails.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 220, -1));

        jSeparator15.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 220, -1));

        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 153, 51));
        jTextField15.setBorder(null);
        TabClientDetails.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 220, -1));

        jSeparator16.setForeground(new java.awt.Color(102, 102, 102));
        TabClientDetails.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 220, -1));

        jTextField16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField16.setForeground(new java.awt.Color(255, 153, 51));
        jTextField16.setBorder(null);
        TabClientDetails.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 220, -1));

        rbMarried.setBackground(new java.awt.Color(255, 255, 255));
        rbMarried.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        rbMarried.setForeground(new java.awt.Color(255, 153, 51));
        rbMarried.setText("Married");
        rbMarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMarriedActionPerformed(evt);
            }
        });
        TabClientDetails.add(rbMarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, 30));

        rbSingle.setBackground(new java.awt.Color(255, 255, 255));
        rbSingle.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        rbSingle.setForeground(new java.awt.Color(255, 153, 51));
        rbSingle.setSelected(true);
        rbSingle.setText("Single");
        rbSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSingleActionPerformed(evt);
            }
        });
        TabClientDetails.add(rbSingle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 30));

        jTabbedPane1.addTab("Client Information", TabClientDetails);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerWitness.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        headerWitness.setForeground(new java.awt.Color(102, 102, 102));
        headerWitness.setText("Witness Information");
        jPanel1.add(headerWitness, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblWitness1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblWitness1.setForeground(new java.awt.Color(102, 102, 102));
        lblWitness1.setText("Witness 1:");
        lblWitness1.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel1.add(lblWitness1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 90, -1));

        jSeparator11.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 220, -1));

        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 153, 51));
        jTextField11.setBorder(null);
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 220, -1));

        jSeparator13.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, -1));

        jTextField13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 153, 51));
        jTextField13.setBorder(null);
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, -1));

        lblWitness2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblWitness2.setForeground(new java.awt.Color(102, 102, 102));
        lblWitness2.setText("Witness 2:");
        lblWitness2.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel1.add(lblWitness2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 90, -1));

        jTabbedPane1.addTab("Witness Details", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerHouse.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        headerHouse.setForeground(new java.awt.Color(102, 102, 102));
        headerHouse.setText("Payment Information");
        jPanel2.add(headerHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        lblName1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName1.setForeground(new java.awt.Color(102, 102, 102));
        lblName1.setText("Model:");
        lblName1.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 70, -1));

        tfName1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName1.setForeground(new java.awt.Color(255, 153, 51));
        tfName1.setBorder(null);
        jPanel2.add(tfName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 220, -1));

        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 220, -1));

        lblName2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName2.setForeground(new java.awt.Color(102, 102, 102));
        lblName2.setText("Location:");
        lblName2.setToolTipText("");
        lblName2.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 70, -1));

        tfName2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName2.setForeground(new java.awt.Color(255, 153, 51));
        tfName2.setBorder(null);
        jPanel2.add(tfName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 220, -1));

        jSeparator5.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 220, -1));

        lblName3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName3.setForeground(new java.awt.Color(102, 102, 102));
        lblName3.setText("Lot Area:");
        lblName3.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, -1));

        tfName3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName3.setForeground(new java.awt.Color(255, 153, 51));
        tfName3.setBorder(null);
        jPanel2.add(tfName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 220, -1));

        jSeparator8.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 220, -1));

        lblName4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName4.setForeground(new java.awt.Color(102, 102, 102));
        lblName4.setText("Floor Area:");
        lblName4.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 80, -1));

        jSeparator12.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 220, -1));

        tfName4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName4.setForeground(new java.awt.Color(255, 153, 51));
        tfName4.setBorder(null);
        jPanel2.add(tfName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 220, -1));

        tfName5.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName5.setForeground(new java.awt.Color(255, 153, 51));
        tfName5.setBorder(null);
        jPanel2.add(tfName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, -1));

        lblName5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName5.setForeground(new java.awt.Color(102, 102, 102));
        lblName5.setText("Lot No.:");
        lblName5.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 70, -1));

        jSeparator17.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 220, -1));

        lblName6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName6.setForeground(new java.awt.Color(102, 102, 102));
        lblName6.setText("Blk. No.:");
        lblName6.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 70, -1));

        tfName6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName6.setForeground(new java.awt.Color(255, 153, 51));
        tfName6.setBorder(null);
        jPanel2.add(tfName6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 220, -1));

        jSeparator18.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 220, -1));

        lblName7.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName7.setForeground(new java.awt.Color(102, 102, 102));
        lblName7.setText("Title No.:");
        lblName7.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 70, -1));

        tfName7.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName7.setForeground(new java.awt.Color(255, 153, 51));
        tfName7.setBorder(null);
        jPanel2.add(tfName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 220, -1));

        tfName8.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName8.setForeground(new java.awt.Color(255, 153, 51));
        tfName8.setBorder(null);
        jPanel2.add(tfName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 220, -1));

        lblName8.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName8.setForeground(new java.awt.Color(102, 102, 102));
        lblName8.setText("Bedroom:");
        lblName8.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 70, -1));

        jSeparator19.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 220, -1));

        jSeparator20.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 220, -1));

        lblName9.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName9.setForeground(new java.awt.Color(102, 102, 102));
        lblName9.setText("Amount:");
        lblName9.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 70, -1));

        tfName9.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName9.setForeground(new java.awt.Color(255, 153, 51));
        tfName9.setBorder(null);
        jPanel2.add(tfName9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 220, -1));

        jSeparator21.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 220, -1));

        headerHouse1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        headerHouse1.setForeground(new java.awt.Color(102, 102, 102));
        headerHouse1.setText("House Information");
        jPanel2.add(headerHouse1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblName10.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName10.setForeground(new java.awt.Color(102, 102, 102));
        lblName10.setText("Amount:");
        lblName10.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 70, -1));

        tfName10.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName10.setForeground(new java.awt.Color(255, 153, 51));
        tfName10.setBorder(null);
        jPanel2.add(tfName10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 220, -1));

        jSeparator22.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 220, -1));

        lblName11.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName11.setForeground(new java.awt.Color(102, 102, 102));
        lblName11.setText("Reservation:");
        lblName11.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 90, -1));

        lblName12.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName12.setForeground(new java.awt.Color(102, 102, 102));
        lblName12.setText("Downpayment:");
        lblName12.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 110, -1));

        lblName13.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName13.setForeground(new java.awt.Color(102, 102, 102));
        lblName13.setText("Balance:");
        lblName13.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 70, -1));

        tfName11.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName11.setForeground(new java.awt.Color(255, 153, 51));
        tfName11.setBorder(null);
        jPanel2.add(tfName11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 220, -1));

        jSeparator23.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 220, -1));

        tfName12.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName12.setForeground(new java.awt.Color(255, 153, 51));
        tfName12.setBorder(null);
        jPanel2.add(tfName12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 220, -1));

        jSeparator24.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 220, -1));

        tfName13.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName13.setForeground(new java.awt.Color(255, 153, 51));
        tfName13.setBorder(null);
        jPanel2.add(tfName13, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 220, -1));

        jSeparator25.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator25, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 220, -1));

        headerHouse2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        headerHouse2.setForeground(new java.awt.Color(102, 102, 102));
        headerHouse2.setText("Broker Information:");
        jPanel2.add(headerHouse2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        lblName14.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName14.setForeground(new java.awt.Color(102, 102, 102));
        lblName14.setText("Realty:");
        lblName14.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 70, -1));

        tfName14.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName14.setForeground(new java.awt.Color(255, 153, 51));
        tfName14.setBorder(null);
        jPanel2.add(tfName14, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 220, -1));

        jSeparator26.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 220, -1));

        lblName15.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName15.setForeground(new java.awt.Color(102, 102, 102));
        lblName15.setText("Agent Name:");
        lblName15.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 90, -1));

        tfName15.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName15.setForeground(new java.awt.Color(255, 153, 51));
        tfName15.setBorder(null);
        jPanel2.add(tfName15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 220, -1));

        jSeparator27.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 220, -1));

        lblName16.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblName16.setForeground(new java.awt.Color(102, 102, 102));
        lblName16.setText("Contact No.:");
        lblName16.setPreferredSize(new java.awt.Dimension(43, 25));
        jPanel2.add(lblName16, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 110, -1));

        tfName16.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        tfName16.setForeground(new java.awt.Color(255, 153, 51));
        tfName16.setBorder(null);
        jPanel2.add(tfName16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 220, -1));

        jSeparator28.setForeground(new java.awt.Color(102, 102, 102));
        jPanel2.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 220, -1));

        jTabbedPane1.addTab("House Details", jPanel2);

        add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void rbMarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMarriedActionPerformed
        if(rbMarried.isSelected()){
            setSpouseToVisible(true);
        }
    }//GEN-LAST:event_rbMarriedActionPerformed

    private void rbSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSingleActionPerformed
        if(rbSingle.isSelected()){
            setSpouseToVisible(false);
        }
    }//GEN-LAST:event_rbSingleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel TabClientDetails;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel headerClient;
    private javax.swing.JLabel headerHouse;
    private javax.swing.JLabel headerHouse1;
    private javax.swing.JLabel headerHouse2;
    private javax.swing.JLabel headerSpousePartner;
    private javax.swing.JLabel headerWitness;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblCivilStatus;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblIDNumber;
    private javax.swing.JLabel lblIDType;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName10;
    private javax.swing.JLabel lblName11;
    private javax.swing.JLabel lblName12;
    private javax.swing.JLabel lblName13;
    private javax.swing.JLabel lblName14;
    private javax.swing.JLabel lblName15;
    private javax.swing.JLabel lblName16;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblName5;
    private javax.swing.JLabel lblName6;
    private javax.swing.JLabel lblName7;
    private javax.swing.JLabel lblName8;
    private javax.swing.JLabel lblName9;
    private javax.swing.JLabel lblSpouseIDNo;
    private javax.swing.JLabel lblSpouseIDType;
    private javax.swing.JLabel lblSpouseName;
    private javax.swing.JLabel lblWitness1;
    private javax.swing.JLabel lblWitness2;
    private javax.swing.JRadioButton rbMarried;
    private javax.swing.JRadioButton rbSingle;
    private javax.swing.JTextField tdIdType;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfIdNumber;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfName1;
    private javax.swing.JTextField tfName10;
    private javax.swing.JTextField tfName11;
    private javax.swing.JTextField tfName12;
    private javax.swing.JTextField tfName13;
    private javax.swing.JTextField tfName14;
    private javax.swing.JTextField tfName15;
    private javax.swing.JTextField tfName16;
    private javax.swing.JTextField tfName2;
    private javax.swing.JTextField tfName3;
    private javax.swing.JTextField tfName4;
    private javax.swing.JTextField tfName5;
    private javax.swing.JTextField tfName6;
    private javax.swing.JTextField tfName7;
    private javax.swing.JTextField tfName8;
    private javax.swing.JTextField tfName9;
    // End of variables declaration//GEN-END:variables

    private void setSpouseToVisible(boolean flag){
        headerSpousePartner.setVisible(flag);
        lblSpouseName.setVisible(flag);
        lblSpouseIDNo.setVisible(flag);
        lblSpouseIDType.setVisible(flag);
        jSeparator14.setVisible(flag);
        jSeparator15.setVisible(flag);
        jSeparator16.setVisible(flag);
    }
}
