/*
 * INCOGNITO CONFIDENTIAL 
 * 
 * [2018] Incognito Solutions 
 * All Rights Reserved.
 * 
 * NOTICE:  All information contained herein is, and remains
 * the property of Incognito Solutions and its client.
 * The intellectual and technical concepts contained
 * herein are proprietary to Adobe Systems Incorporated
 * and its client and may be covered by U.S. and Foreign Patents
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Incognito Solutions.
 */
package ph.com.incognitosolutions.aei.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author loretizoj
 */
public class Dashboard extends javax.swing.JFrame {
    
    private final String IMAGE_LOCATIONS = "/ph/com/incognitosolutions/gui/icons/";
    
    int xMouse;
    int yMouse;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        lblOptionOne.setText("");
        lblOptionTwo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        lblCompany = new javax.swing.JLabel();
        paneHome = new javax.swing.JPanel();
        icoHome = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        paneBroker = new javax.swing.JPanel();
        icoBroker = new javax.swing.JLabel();
        lblBroker = new javax.swing.JLabel();
        paneEmployee = new javax.swing.JPanel();
        icoEmployee = new javax.swing.JLabel();
        lblEmployee = new javax.swing.JLabel();
        paneTemplates = new javax.swing.JPanel();
        icoTemplates = new javax.swing.JLabel();
        lblTemplates = new javax.swing.JLabel();
        paneHouse = new javax.swing.JPanel();
        icoHouse = new javax.swing.JLabel();
        lblHouse = new javax.swing.JLabel();
        panePayment = new javax.swing.JPanel();
        icoPayment = new javax.swing.JLabel();
        lblPayment = new javax.swing.JLabel();
        paneClient = new javax.swing.JPanel();
        icoClient = new javax.swing.JLabel();
        lblClient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        topbarPanel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblTabLabel = new javax.swing.JLabel();
        lblOptionTwo = new javax.swing.JLabel();
        lblOptionOne = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(255, 153, 51));
        sidePanel.setPreferredSize(new java.awt.Dimension(200, 720));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCompany.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(255, 255, 255));
        lblCompany.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompany.setText("AE International");
        sidePanel.add(lblCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 200, -1));

        paneHome.setBackground(new java.awt.Color(255, 204, 153));
        paneHome.setPreferredSize(new java.awt.Dimension(200, 52));
        paneHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneHomeMouseClicked(evt);
            }
        });

        icoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/home_selected.png"))); // NOI18N

        lblHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblHome.setForeground(new java.awt.Color(51, 51, 255));
        lblHome.setText("Home");

        javax.swing.GroupLayout paneHomeLayout = new javax.swing.GroupLayout(paneHome);
        paneHome.setLayout(paneHomeLayout);
        paneHomeLayout.setHorizontalGroup(
            paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHomeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icoHome)
                .addGap(18, 18, 18)
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        paneHomeLayout.setVerticalGroup(
            paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icoHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(paneHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 200, -1));

        paneBroker.setBackground(new java.awt.Color(255, 153, 0));
        paneBroker.setPreferredSize(new java.awt.Dimension(200, 52));
        paneBroker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneBrokerMouseClicked(evt);
            }
        });

        icoBroker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/broker.png"))); // NOI18N

        lblBroker.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblBroker.setForeground(new java.awt.Color(255, 255, 255));
        lblBroker.setText("Broker");

        javax.swing.GroupLayout paneBrokerLayout = new javax.swing.GroupLayout(paneBroker);
        paneBroker.setLayout(paneBrokerLayout);
        paneBrokerLayout.setHorizontalGroup(
            paneBrokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBrokerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icoBroker)
                .addGap(18, 18, 18)
                .addComponent(lblBroker, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        paneBrokerLayout.setVerticalGroup(
            paneBrokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneBrokerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneBrokerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icoBroker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBroker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(paneBroker, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 200, -1));

        paneEmployee.setBackground(new java.awt.Color(255, 153, 0));
        paneEmployee.setPreferredSize(new java.awt.Dimension(200, 52));
        paneEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneEmployeeMouseClicked(evt);
            }
        });

        icoEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/employee.png"))); // NOI18N

        lblEmployee.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lblEmployee.setText("Employee");

        javax.swing.GroupLayout paneEmployeeLayout = new javax.swing.GroupLayout(paneEmployee);
        paneEmployee.setLayout(paneEmployeeLayout);
        paneEmployeeLayout.setHorizontalGroup(
            paneEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEmployeeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icoEmployee)
                .addGap(18, 18, 18)
                .addComponent(lblEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        paneEmployeeLayout.setVerticalGroup(
            paneEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icoEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(paneEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 200, -1));

        paneTemplates.setBackground(new java.awt.Color(255, 153, 0));
        paneTemplates.setPreferredSize(new java.awt.Dimension(200, 52));
        paneTemplates.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneTemplatesMouseClicked(evt);
            }
        });

        icoTemplates.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/templates.png"))); // NOI18N

        lblTemplates.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblTemplates.setForeground(new java.awt.Color(255, 255, 255));
        lblTemplates.setText("Templates");

        javax.swing.GroupLayout paneTemplatesLayout = new javax.swing.GroupLayout(paneTemplates);
        paneTemplates.setLayout(paneTemplatesLayout);
        paneTemplatesLayout.setHorizontalGroup(
            paneTemplatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTemplatesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icoTemplates)
                .addGap(18, 18, 18)
                .addComponent(lblTemplates, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        paneTemplatesLayout.setVerticalGroup(
            paneTemplatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneTemplatesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneTemplatesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icoTemplates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTemplates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(paneTemplates, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 200, -1));

        paneHouse.setBackground(new java.awt.Color(255, 153, 0));
        paneHouse.setPreferredSize(new java.awt.Dimension(200, 52));
        paneHouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneHouseMouseClicked(evt);
            }
        });

        icoHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/house.png"))); // NOI18N

        lblHouse.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblHouse.setForeground(new java.awt.Color(255, 255, 255));
        lblHouse.setText("House");

        javax.swing.GroupLayout paneHouseLayout = new javax.swing.GroupLayout(paneHouse);
        paneHouse.setLayout(paneHouseLayout);
        paneHouseLayout.setHorizontalGroup(
            paneHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHouseLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icoHouse)
                .addGap(18, 18, 18)
                .addComponent(lblHouse, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        paneHouseLayout.setVerticalGroup(
            paneHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneHouseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneHouseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icoHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(paneHouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 200, -1));

        panePayment.setBackground(new java.awt.Color(255, 153, 0));
        panePayment.setPreferredSize(new java.awt.Dimension(200, 52));
        panePayment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panePaymentMouseClicked(evt);
            }
        });

        icoPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/payment.png"))); // NOI18N

        lblPayment.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblPayment.setForeground(new java.awt.Color(255, 255, 255));
        lblPayment.setText("Payment");

        javax.swing.GroupLayout panePaymentLayout = new javax.swing.GroupLayout(panePayment);
        panePayment.setLayout(panePaymentLayout);
        panePaymentLayout.setHorizontalGroup(
            panePaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePaymentLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icoPayment)
                .addGap(18, 18, 18)
                .addComponent(lblPayment, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        panePaymentLayout.setVerticalGroup(
            panePaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePaymentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icoPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(panePayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 200, -1));

        paneClient.setBackground(new java.awt.Color(255, 153, 0));
        paneClient.setPreferredSize(new java.awt.Dimension(200, 52));
        paneClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneClientMouseClicked(evt);
            }
        });

        icoClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/client.png"))); // NOI18N

        lblClient.setBackground(new java.awt.Color(251, 123, 57));
        lblClient.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblClient.setForeground(new java.awt.Color(255, 255, 255));
        lblClient.setText("Client");

        javax.swing.GroupLayout paneClientLayout = new javax.swing.GroupLayout(paneClient);
        paneClient.setLayout(paneClientLayout);
        paneClientLayout.setHorizontalGroup(
            paneClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneClientLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(icoClient)
                .addGap(18, 18, 18)
                .addComponent(lblClient, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(31, 31, 31))
        );
        paneClientLayout.setVerticalGroup(
            paneClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneClientLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(icoClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidePanel.add(paneClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 200, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/logo.png"))); // NOI18N
        sidePanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, 70));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        topbarPanel.setPreferredSize(new java.awt.Dimension(34, 20));
        topbarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                topbarPanelMouseDragged(evt);
            }
        });
        topbarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                topbarPanelMousePressed(evt);
            }
        });
        getContentPane().add(topbarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 30));

        topPanel.setBackground(new java.awt.Color(255, 255, 255));
        topPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblMinimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/minimize.png"))); // NOI18N
        lblMinimize.setToolTipText("Close");
        lblMinimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblMinimize.setIconTextGap(0);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        topPanel.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 30, 30));

        lblExit.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ph/com/incognitosolutions/gui/icons/close.png"))); // NOI18N
        lblExit.setToolTipText("Close");
        lblExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblExit.setIconTextGap(0);
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExitMousePressed(evt);
            }
        });
        topPanel.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, 30, 30));

        lblTabLabel.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblTabLabel.setForeground(new java.awt.Color(255, 153, 51));
        lblTabLabel.setText("DASHBOARD");
        topPanel.add(lblTabLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        lblOptionTwo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblOptionTwo.setForeground(new java.awt.Color(102, 102, 102));
        lblOptionTwo.setText("View Employee");
        topPanel.add(lblOptionTwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        lblOptionOne.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblOptionOne.setForeground(java.awt.Color.blue);
        lblOptionOne.setText("Add Employee");
        topPanel.add(lblOptionOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 25));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        topPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 800, 80));

        getContentPane().add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 810, 140));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.BorderLayout());
        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 800, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void topbarPanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarPanelMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_topbarPanelMouseDragged

    private void topbarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_topbarPanelMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_topbarPanelMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
       // minimize
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblExitMousePressed

    private void paneClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneClientMouseClicked
        lblTabLabel.setText("MANAGE CLIENTS");
        lblOptionOne.setText("Add Client");
        lblOptionTwo.setText("View Client");
        openClientPage();
        setToSelected(lblClient, paneClient);
        icoClient.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "client-selected.png")));
    }//GEN-LAST:event_paneClientMouseClicked

    private void paneHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHomeMouseClicked
        lblTabLabel.setText("DASHBOARD");
        lblOptionOne.setText("");
        lblOptionTwo.setText("");
        setToSelected(lblHome, paneHome);
        icoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "home_selected.png")));
        removeCurrComponent();
    }//GEN-LAST:event_paneHomeMouseClicked

    private void panePaymentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panePaymentMouseClicked
        lblTabLabel.setText("MANAGE PAYMENTS");
        lblOptionOne.setText("Add Payment");
        lblOptionTwo.setText("View Payment");
        openPaymentPage();
        setToSelected(lblPayment, panePayment);
        icoPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "payment-selected.png")));
    }//GEN-LAST:event_panePaymentMouseClicked

    private void paneTemplatesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneTemplatesMouseClicked
        lblTabLabel.setText("PRINT TEMPLATES");
        setToSelected(lblTemplates, paneTemplates);
        icoTemplates.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "templates-selected.png")));
    }//GEN-LAST:event_paneTemplatesMouseClicked

    private void paneHouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneHouseMouseClicked
        lblTabLabel.setText("MANAGE HOUSE");
        setToSelected(lblHouse, paneHouse);
        icoHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "house-selected.png")));
    }//GEN-LAST:event_paneHouseMouseClicked

    private void paneBrokerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneBrokerMouseClicked
        lblTabLabel.setText("MANAGE BROKER");
        setToSelected(lblBroker, paneBroker);
        icoBroker.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "broker-selected.png")));
    }//GEN-LAST:event_paneBrokerMouseClicked

    private void paneEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneEmployeeMouseClicked
        lblTabLabel.setText("MANAGE EMPLOYEE");
        setToSelected(lblEmployee, paneEmployee);
        icoEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "employee-selected.png")));
    }//GEN-LAST:event_paneEmployeeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    
    private void setButtonForeGroundWhite() {
        lblBroker.setForeground(Color.WHITE);
        lblClient.setForeground(Color.WHITE);
        lblHouse.setForeground(Color.WHITE);
        lblEmployee.setForeground(Color.WHITE);
        lblHome.setForeground(Color.WHITE);
        lblPayment.setForeground(Color.WHITE);
        lblTemplates.setForeground(Color.WHITE);
    }
    
    private void setDefaultIcon() {
        icoBroker.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "broker.png")));
        icoClient.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "client.png")));
        icoEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "employee.png")));
        icoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "home.png")));
        icoHouse.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "house.png")));
        icoPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "payment.png")));
        icoTemplates.setIcon(new javax.swing.ImageIcon(getClass().getResource(IMAGE_LOCATIONS + "templates.png")));
    }
    
    private void setPaneColorDefault(){
        paneBroker.setBackground(new java.awt.Color(255, 153, 51));
        paneClient.setBackground(new java.awt.Color(255, 153, 51));
        paneEmployee.setBackground(new java.awt.Color(255, 153, 51));
        paneHome.setBackground(new java.awt.Color(255, 153, 51));
        paneHouse.setBackground(new java.awt.Color(255, 153, 51));
        panePayment.setBackground(new java.awt.Color(255, 153, 51));
        paneTemplates.setBackground(new java.awt.Color(255, 153, 51));
    }
    
    private void setToSelected(JLabel jLabel, JPanel jPanel){
        setButtonForeGroundWhite();
        setDefaultIcon();
        setPaneColorDefault();
        jLabel.setForeground(new java.awt.Color(51, 51, 255));
        jPanel.setBackground(new java.awt.Color(255, 204, 153));
    }
    
    private void openClientPage() {
        ClientPanel clientPanel = new ClientPanel();
        removeCurrComponent();
        clientPanel.show();
        mainPanel.add(clientPanel);
        mainPanel.updateUI();
    }
    
    private void openPaymentPage() {
        PaymentPanel paymentPanel = new PaymentPanel();
        removeCurrComponent();
        paymentPanel.show();
        mainPanel.add(paymentPanel);
        mainPanel.updateUI();
    }
    
    private void removeCurrComponent() {
        Component[] comp = this.mainPanel.getComponents();
        if (comp.length != 0) {
            mainPanel.remove(comp[0]);
            mainPanel.updateUI();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icoBroker;
    private javax.swing.JLabel icoClient;
    private javax.swing.JLabel icoEmployee;
    private javax.swing.JLabel icoHome;
    private javax.swing.JLabel icoHouse;
    private javax.swing.JLabel icoPayment;
    private javax.swing.JLabel icoTemplates;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBroker;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHouse;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblOptionOne;
    private javax.swing.JLabel lblOptionTwo;
    private javax.swing.JLabel lblPayment;
    private javax.swing.JLabel lblTabLabel;
    private javax.swing.JLabel lblTemplates;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel paneBroker;
    private javax.swing.JPanel paneClient;
    private javax.swing.JPanel paneEmployee;
    private javax.swing.JPanel paneHome;
    private javax.swing.JPanel paneHouse;
    private javax.swing.JPanel panePayment;
    private javax.swing.JPanel paneTemplates;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel topbarPanel;
    // End of variables declaration//GEN-END:variables
}
